/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRelayer,
  IRelayerInterface,
} from "../../../../network/extensions/relayer/IRelayer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "destChain",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "destAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "receiveCrosschainSupply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "destChain",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "destAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "sendCrosschainSupply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRelayer__factory {
  static readonly abi = _abi;
  static createInterface(): IRelayerInterface {
    return new Interface(_abi) as IRelayerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRelayer {
    return new Contract(address, _abi, runner) as unknown as IRelayer;
  }
}
