/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface NodeTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHAIN_ID"
      | "addresses"
      | "allowance"
      | "approve"
      | "availableFromTime"
      | "availableFromVote"
      | "balanceOf"
      | "currentResource1"
      | "currentResource2"
      | "decimals"
      | "entryFacet"
      | "getAllRemoteSupplies"
      | "getEntryFacet"
      | "getGlobalSupply"
      | "getPendingTimelock"
      | "getPendingVotes"
      | "getRelayer"
      | "getResourceByTimelock"
      | "getResourceByVotes"
      | "hasVoted"
      | "knownChains"
      | "myRelayer"
      | "name"
      | "owner"
      | "proposalVotes"
      | "receiveCrosschainTransaction"
      | "receiveSyncNodesTransaction"
      | "scheduleByTimelock"
      | "scheduleByVotes"
      | "setEntryFacet"
      | "setReceiveFacet"
      | "setRelayer"
      | "supplies"
      | "symbol"
      | "timelockedResource"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "vote"
      | "votedResource"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "FacetUpdated"
      | "LocalSupplyUpdated"
      | "RelayerUpdated"
      | "RemoteSupplyUpdated"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(functionFragment: "CHAIN_ID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "availableFromTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "availableFromVote",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentResource1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentResource2",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "entryFacet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRemoteSupplies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryFacet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingTimelock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getResourceByTimelock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getResourceByVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "knownChains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "myRelayer", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalVotes",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveCrosschainTransaction",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveSyncNodesTransaction",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleByTimelock",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleByVotes",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setEntryFacet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReceiveFacet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supplies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timelockedResource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "vote", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "votedResource",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "CHAIN_ID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addresses", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "availableFromTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableFromVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentResource1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentResource2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "entryFacet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllRemoteSupplies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryFacet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getResourceByTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResourceByVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "knownChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "myRelayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveCrosschainTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveSyncNodesTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleByTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleByVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEntryFacet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReceiveFacet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "supplies", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "timelockedResource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votedResource",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FacetUpdatedEvent {
  export type InputTuple = [
    oldImplementation: AddressLike,
    newImplementation: AddressLike
  ];
  export type OutputTuple = [
    oldImplementation: string,
    newImplementation: string
  ];
  export interface OutputObject {
    oldImplementation: string;
    newImplementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LocalSupplyUpdatedEvent {
  export type InputTuple = [chainId: BigNumberish, newSupply: BigNumberish];
  export type OutputTuple = [chainId: bigint, newSupply: bigint];
  export interface OutputObject {
    chainId: bigint;
    newSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerUpdatedEvent {
  export type InputTuple = [
    oldImplementation: AddressLike,
    newImplementation: AddressLike
  ];
  export type OutputTuple = [
    oldImplementation: string,
    newImplementation: string
  ];
  export interface OutputObject {
    oldImplementation: string;
    newImplementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoteSupplyUpdatedEvent {
  export type InputTuple = [chainId: BigNumberish, newSupply: BigNumberish];
  export type OutputTuple = [chainId: bigint, newSupply: bigint];
  export interface OutputObject {
    chainId: bigint;
    newSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NodeToken extends BaseContract {
  connect(runner?: ContractRunner | null): NodeToken;
  waitForDeployment(): Promise<this>;

  interface: NodeTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHAIN_ID: TypedContractMethod<[], [bigint], "view">;

  addresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  allowance: TypedContractMethod<
    [owner_: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  availableFromTime: TypedContractMethod<[], [bigint], "view">;

  availableFromVote: TypedContractMethod<[], [bigint], "view">;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  currentResource1: TypedContractMethod<[], [string], "view">;

  currentResource2: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  entryFacet: TypedContractMethod<[], [string], "view">;

  getAllRemoteSupplies: TypedContractMethod<
    [],
    [[bigint[], bigint[]] & { chainIds: bigint[]; _supplies: bigint[] }],
    "view"
  >;

  getEntryFacet: TypedContractMethod<[], [string], "view">;

  getGlobalSupply: TypedContractMethod<[], [bigint], "view">;

  getPendingTimelock: TypedContractMethod<[], [[string, bigint]], "view">;

  getPendingVotes: TypedContractMethod<[], [[string, bigint]], "view">;

  getRelayer: TypedContractMethod<[], [string], "view">;

  getResourceByTimelock: TypedContractMethod<[], [string], "nonpayable">;

  getResourceByVotes: TypedContractMethod<[], [string], "nonpayable">;

  hasVoted: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [boolean],
    "view"
  >;

  knownChains: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  myRelayer: TypedContractMethod<[], [string], "view">;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proposalVotes: TypedContractMethod<[arg0: string], [bigint], "view">;

  receiveCrosschainTransaction: TypedContractMethod<
    [sourceChain: BigNumberish, destChain: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  receiveSyncNodesTransaction: TypedContractMethod<
    [sourceChain: BigNumberish, destChain: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  scheduleByTimelock: TypedContractMethod<[_new: string], [void], "nonpayable">;

  scheduleByVotes: TypedContractMethod<[_new: string], [void], "nonpayable">;

  setEntryFacet: TypedContractMethod<
    [_newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  setReceiveFacet: TypedContractMethod<
    [receiveFacet_: AddressLike],
    [void],
    "nonpayable"
  >;

  setRelayer: TypedContractMethod<
    [_newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  supplies: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  timelockedResource: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  vote: TypedContractMethod<[], [void], "nonpayable">;

  votedResource: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHAIN_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner_: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "availableFromTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "availableFromVote"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentResource1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentResource2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entryFacet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllRemoteSupplies"
  ): TypedContractMethod<
    [],
    [[bigint[], bigint[]] & { chainIds: bigint[]; _supplies: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntryFacet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getGlobalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingTimelock"
  ): TypedContractMethod<[], [[string, bigint]], "view">;
  getFunction(
    nameOrSignature: "getPendingVotes"
  ): TypedContractMethod<[], [[string, bigint]], "view">;
  getFunction(
    nameOrSignature: "getRelayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getResourceByTimelock"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getResourceByVotes"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "knownChains"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "myRelayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposalVotes"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "receiveCrosschainTransaction"
  ): TypedContractMethod<
    [sourceChain: BigNumberish, destChain: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveSyncNodesTransaction"
  ): TypedContractMethod<
    [sourceChain: BigNumberish, destChain: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleByTimelock"
  ): TypedContractMethod<[_new: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scheduleByVotes"
  ): TypedContractMethod<[_new: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEntryFacet"
  ): TypedContractMethod<
    [_newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReceiveFacet"
  ): TypedContractMethod<[receiveFacet_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<
    [_newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supplies"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timelockedResource"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "votedResource"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "FacetUpdated"
  ): TypedContractEvent<
    FacetUpdatedEvent.InputTuple,
    FacetUpdatedEvent.OutputTuple,
    FacetUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LocalSupplyUpdated"
  ): TypedContractEvent<
    LocalSupplyUpdatedEvent.InputTuple,
    LocalSupplyUpdatedEvent.OutputTuple,
    LocalSupplyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerUpdated"
  ): TypedContractEvent<
    RelayerUpdatedEvent.InputTuple,
    RelayerUpdatedEvent.OutputTuple,
    RelayerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RemoteSupplyUpdated"
  ): TypedContractEvent<
    RemoteSupplyUpdatedEvent.InputTuple,
    RemoteSupplyUpdatedEvent.OutputTuple,
    RemoteSupplyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "FacetUpdated(address,address)": TypedContractEvent<
      FacetUpdatedEvent.InputTuple,
      FacetUpdatedEvent.OutputTuple,
      FacetUpdatedEvent.OutputObject
    >;
    FacetUpdated: TypedContractEvent<
      FacetUpdatedEvent.InputTuple,
      FacetUpdatedEvent.OutputTuple,
      FacetUpdatedEvent.OutputObject
    >;

    "LocalSupplyUpdated(uint256,uint256)": TypedContractEvent<
      LocalSupplyUpdatedEvent.InputTuple,
      LocalSupplyUpdatedEvent.OutputTuple,
      LocalSupplyUpdatedEvent.OutputObject
    >;
    LocalSupplyUpdated: TypedContractEvent<
      LocalSupplyUpdatedEvent.InputTuple,
      LocalSupplyUpdatedEvent.OutputTuple,
      LocalSupplyUpdatedEvent.OutputObject
    >;

    "RelayerUpdated(address,address)": TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;
    RelayerUpdated: TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;

    "RemoteSupplyUpdated(uint256,uint256)": TypedContractEvent<
      RemoteSupplyUpdatedEvent.InputTuple,
      RemoteSupplyUpdatedEvent.OutputTuple,
      RemoteSupplyUpdatedEvent.OutputObject
    >;
    RemoteSupplyUpdated: TypedContractEvent<
      RemoteSupplyUpdatedEvent.InputTuple,
      RemoteSupplyUpdatedEvent.OutputTuple,
      RemoteSupplyUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
