/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fungibleEnvironmentSol from "./FungibleEnvironment.sol";
export type { fungibleEnvironmentSol };
export type { DemoPaymentToken } from "./DemoPaymentToken";
