/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface BridgeRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "chains"
      | "completeCrossChainTransfer"
      | "getChainInfo"
      | "getTransfer"
      | "initiateCrossChainTransfer"
      | "owner"
      | "processedTransactions"
      | "registerChain"
      | "setChainActive"
      | "totalChains"
      | "transfers"
      | "updateRequiredValidators"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChainRegistered"
      | "CrossChainTransferInitiated"
      | "TransferCompleted"
      | "TransferFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "chains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeCrossChainTransfer",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransfer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateCrossChainTransfer",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processedTransactions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerChain",
    values: [BigNumberish, AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setChainActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalChains",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRequiredValidators",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "chains", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeCrossChainTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateCrossChainTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChainActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRequiredValidators",
    data: BytesLike
  ): Result;
}

export namespace ChainRegisteredEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    nodeContract: AddressLike,
    name: string
  ];
  export type OutputTuple = [
    chainId: bigint,
    nodeContract: string,
    name: string
  ];
  export interface OutputObject {
    chainId: bigint;
    nodeContract: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainTransferInitiatedEvent {
  export type InputTuple = [
    txHash: BytesLike,
    fromChain: BigNumberish,
    toChain: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    txHash: string,
    fromChain: bigint,
    toChain: bigint,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    txHash: string;
    fromChain: bigint;
    toChain: bigint;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferCompletedEvent {
  export type InputTuple = [txHash: BytesLike];
  export type OutputTuple = [txHash: string];
  export interface OutputObject {
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferFailedEvent {
  export type InputTuple = [txHash: BytesLike, reason: string];
  export type OutputTuple = [txHash: string, reason: string];
  export interface OutputObject {
    txHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BridgeRouter extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeRouter;
  waitForDeployment(): Promise<this>;

  interface: BridgeRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  chains: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, bigint, string] & {
        nodeContract: string;
        lastBlockSynced: bigint;
        isActive: boolean;
        requiredValidators: bigint;
        name: string;
      }
    ],
    "view"
  >;

  completeCrossChainTransfer: TypedContractMethod<
    [txHash: BytesLike, signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  getChainInfo: TypedContractMethod<
    [chainId: BigNumberish],
    [
      [string, bigint, boolean, bigint, string] & {
        nodeContract: string;
        lastBlockSynced: bigint;
        isActive: boolean;
        requiredValidators: bigint;
        name: string;
      }
    ],
    "view"
  >;

  getTransfer: TypedContractMethod<
    [txHash: BytesLike],
    [
      [string, bigint, bigint, string, string, bigint, bigint, bigint] & {
        _txHash: string;
        fromChain: bigint;
        toChain: bigint;
        from: string;
        to: string;
        amount: bigint;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  initiateCrossChainTransfer: TypedContractMethod<
    [toChainId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processedTransactions: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  registerChain: TypedContractMethod<
    [
      chainId: BigNumberish,
      nodeContract: AddressLike,
      name: string,
      requiredValidators: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setChainActive: TypedContractMethod<
    [chainId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  totalChains: TypedContractMethod<[], [bigint], "view">;

  transfers: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string, string, bigint, bigint, bigint] & {
        txHash: string;
        fromChain: bigint;
        toChain: bigint;
        from: string;
        to: string;
        amount: bigint;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  updateRequiredValidators: TypedContractMethod<
    [chainId: BigNumberish, required: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "chains"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, bigint, string] & {
        nodeContract: string;
        lastBlockSynced: bigint;
        isActive: boolean;
        requiredValidators: bigint;
        name: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "completeCrossChainTransfer"
  ): TypedContractMethod<
    [txHash: BytesLike, signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getChainInfo"
  ): TypedContractMethod<
    [chainId: BigNumberish],
    [
      [string, bigint, boolean, bigint, string] & {
        nodeContract: string;
        lastBlockSynced: bigint;
        isActive: boolean;
        requiredValidators: bigint;
        name: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransfer"
  ): TypedContractMethod<
    [txHash: BytesLike],
    [
      [string, bigint, bigint, string, string, bigint, bigint, bigint] & {
        _txHash: string;
        fromChain: bigint;
        toChain: bigint;
        from: string;
        to: string;
        amount: bigint;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateCrossChainTransfer"
  ): TypedContractMethod<
    [toChainId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processedTransactions"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerChain"
  ): TypedContractMethod<
    [
      chainId: BigNumberish,
      nodeContract: AddressLike,
      name: string,
      requiredValidators: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setChainActive"
  ): TypedContractMethod<
    [chainId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalChains"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfers"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string, string, bigint, bigint, bigint] & {
        txHash: string;
        fromChain: bigint;
        toChain: bigint;
        from: string;
        to: string;
        amount: bigint;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateRequiredValidators"
  ): TypedContractMethod<
    [chainId: BigNumberish, required: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ChainRegistered"
  ): TypedContractEvent<
    ChainRegisteredEvent.InputTuple,
    ChainRegisteredEvent.OutputTuple,
    ChainRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainTransferInitiated"
  ): TypedContractEvent<
    CrossChainTransferInitiatedEvent.InputTuple,
    CrossChainTransferInitiatedEvent.OutputTuple,
    CrossChainTransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferCompleted"
  ): TypedContractEvent<
    TransferCompletedEvent.InputTuple,
    TransferCompletedEvent.OutputTuple,
    TransferCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TransferFailed"
  ): TypedContractEvent<
    TransferFailedEvent.InputTuple,
    TransferFailedEvent.OutputTuple,
    TransferFailedEvent.OutputObject
  >;

  filters: {
    "ChainRegistered(uint256,address,string)": TypedContractEvent<
      ChainRegisteredEvent.InputTuple,
      ChainRegisteredEvent.OutputTuple,
      ChainRegisteredEvent.OutputObject
    >;
    ChainRegistered: TypedContractEvent<
      ChainRegisteredEvent.InputTuple,
      ChainRegisteredEvent.OutputTuple,
      ChainRegisteredEvent.OutputObject
    >;

    "CrossChainTransferInitiated(bytes32,uint256,uint256,address,address,uint256)": TypedContractEvent<
      CrossChainTransferInitiatedEvent.InputTuple,
      CrossChainTransferInitiatedEvent.OutputTuple,
      CrossChainTransferInitiatedEvent.OutputObject
    >;
    CrossChainTransferInitiated: TypedContractEvent<
      CrossChainTransferInitiatedEvent.InputTuple,
      CrossChainTransferInitiatedEvent.OutputTuple,
      CrossChainTransferInitiatedEvent.OutputObject
    >;

    "TransferCompleted(bytes32)": TypedContractEvent<
      TransferCompletedEvent.InputTuple,
      TransferCompletedEvent.OutputTuple,
      TransferCompletedEvent.OutputObject
    >;
    TransferCompleted: TypedContractEvent<
      TransferCompletedEvent.InputTuple,
      TransferCompletedEvent.OutputTuple,
      TransferCompletedEvent.OutputObject
    >;

    "TransferFailed(bytes32,string)": TypedContractEvent<
      TransferFailedEvent.InputTuple,
      TransferFailedEvent.OutputTuple,
      TransferFailedEvent.OutputObject
    >;
    TransferFailed: TypedContractEvent<
      TransferFailedEvent.InputTuple,
      TransferFailedEvent.OutputTuple,
      TransferFailedEvent.OutputObject
    >;
  };
}
