/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  EntryFacet,
  EntryFacetInterface,
} from "../../extensions/EntryFacet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "_afterTokenTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "_beforeTokenTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060d180601d6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80638f811a1c146037578063cad3be83146037575b600080fd5b604760423660046064565b505050565b005b80356001600160a01b0381168114605f57600080fd5b919050565b600080600060608486031215607857600080fd5b607f846049565b9250608b602085016049565b915060408401359050925092509256fea2646970667358221220df0cc45c9c25e586ef20fe667dba1e7817cb3444d9eac17443dd8dbaaf6f259a64736f6c634300081e0033";

type EntryFacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EntryFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EntryFacet__factory extends ContractFactory {
  constructor(...args: EntryFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EntryFacet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): EntryFacet__factory {
    return super.connect(runner) as EntryFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EntryFacetInterface {
    return new Interface(_abi) as EntryFacetInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): EntryFacet {
    return new Contract(address, _abi, runner) as unknown as EntryFacet;
  }
}
