/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiamondLoupeFacet__factory } from "./DiamondLoupeFacet__factory";
export { IDiamondLoupe__factory } from "./IDiamondLoupe__factory";
