/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiamondLoupeFacet } from "./DiamondLoupeFacet";
export type { IDiamondLoupe } from "./IDiamondLoupe";
