/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface INodeTokenInterface extends Interface {
  getFunction(nameOrSignature: "getBlock" | "verifyBlock"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBlock",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getBlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyBlock",
    data: BytesLike
  ): Result;
}

export interface INodeToken extends BaseContract {
  connect(runner?: ContractRunner | null): INodeToken;
  waitForDeployment(): Promise<this>;

  interface: INodeTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBlock: TypedContractMethod<
    [blockNumber: BigNumberish],
    [
      [string, bigint, string, bigint, string, string, bigint, string[]] & {
        blockHash: string;
        _blockNumber: bigint;
        previousHash: string;
        timestamp: bigint;
        data: string;
        validator: string;
        _chainId: bigint;
        transactionHashes: string[];
      }
    ],
    "view"
  >;

  verifyBlock: TypedContractMethod<
    [blockNumber: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBlock"
  ): TypedContractMethod<
    [blockNumber: BigNumberish],
    [
      [string, bigint, string, bigint, string, string, bigint, string[]] & {
        blockHash: string;
        _blockNumber: bigint;
        previousHash: string;
        timestamp: bigint;
        data: string;
        validator: string;
        _chainId: bigint;
        transactionHashes: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyBlock"
  ): TypedContractMethod<[blockNumber: BigNumberish], [boolean], "view">;

  filters: {};
}
