/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INodeToken,
  INodeTokenInterface,
} from "../../../token/core/INodeToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sourceChain",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "destChain",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "receiveSyncNodesTransaction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INodeToken__factory {
  static readonly abi = _abi;
  static createInterface(): INodeTokenInterface {
    return new Interface(_abi) as INodeTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INodeToken {
    return new Contract(address, _abi, runner) as unknown as INodeToken;
  }
}
