/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ValidatorNodeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSupportedChain"
      | "depositStake"
      | "getValidation"
      | "getValidatorInfo"
      | "owner"
      | "removeSupportedChain"
      | "setSlashingPercentage"
      | "signTransaction"
      | "slashValidator"
      | "slashingPercentage"
      | "stakes"
      | "supportedChains"
      | "totalStake"
      | "validations"
      | "withdrawStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BlockValidated"
      | "StakeDeposited"
      | "StakeWithdrawn"
      | "ValidatorSlashed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSupportedChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeSupportedChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlashingPercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signTransaction",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slashValidator",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "slashingPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "stakes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "supportedChains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addSupportedChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSlashingPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashingPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportedChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;
}

export namespace BlockValidatedEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    blockNumber: BigNumberish,
    isValid: boolean
  ];
  export type OutputTuple = [
    chainId: bigint,
    blockNumber: bigint,
    isValid: boolean
  ];
  export interface OutputObject {
    chainId: bigint;
    blockNumber: bigint;
    isValid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeDepositedEvent {
  export type InputTuple = [validator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [validator: string, amount: bigint];
  export interface OutputObject {
    validator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeWithdrawnEvent {
  export type InputTuple = [validator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [validator: string, amount: bigint];
  export interface OutputObject {
    validator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorSlashedEvent {
  export type InputTuple = [
    validator: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [validator: string, amount: bigint, reason: string];
  export interface OutputObject {
    validator: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValidatorNode extends BaseContract {
  connect(runner?: ContractRunner | null): ValidatorNode;
  waitForDeployment(): Promise<this>;

  interface: ValidatorNodeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSupportedChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositStake: TypedContractMethod<[], [void], "payable">;

  getValidation: TypedContractMethod<
    [chainId: BigNumberish, blockNumber: BigNumberish],
    [
      [bigint, bigint, string, bigint, boolean] & {
        _chainId: bigint;
        _blockNumber: bigint;
        blockHash: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  getValidatorInfo: TypedContractMethod<
    [validator: AddressLike],
    [
      [bigint, bigint, bigint] & {
        stake: bigint;
        lockedUntil: bigint;
        validationCount: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeSupportedChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSlashingPercentage: TypedContractMethod<
    [percentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  signTransaction: TypedContractMethod<
    [txHash: BytesLike, targetChainId: BigNumberish],
    [string],
    "view"
  >;

  slashValidator: TypedContractMethod<
    [validator: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  slashingPercentage: TypedContractMethod<[], [bigint], "view">;

  stakes: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { amount: bigint; lockedUntil: bigint }],
    "view"
  >;

  supportedChains: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  totalStake: TypedContractMethod<[], [bigint], "view">;

  validations: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, string, bigint, boolean] & {
        chainId: bigint;
        blockNumber: bigint;
        blockHash: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  withdrawStake: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSupportedChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositStake"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getValidation"
  ): TypedContractMethod<
    [chainId: BigNumberish, blockNumber: BigNumberish],
    [
      [bigint, bigint, string, bigint, boolean] & {
        _chainId: bigint;
        _blockNumber: bigint;
        blockHash: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidatorInfo"
  ): TypedContractMethod<
    [validator: AddressLike],
    [
      [bigint, bigint, bigint] & {
        stake: bigint;
        lockedUntil: bigint;
        validationCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeSupportedChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSlashingPercentage"
  ): TypedContractMethod<[percentage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signTransaction"
  ): TypedContractMethod<
    [txHash: BytesLike, targetChainId: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "slashValidator"
  ): TypedContractMethod<
    [validator: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashingPercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { amount: bigint; lockedUntil: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportedChains"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "validations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, string, bigint, boolean] & {
        chainId: bigint;
        blockNumber: bigint;
        blockHash: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawStake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BlockValidated"
  ): TypedContractEvent<
    BlockValidatedEvent.InputTuple,
    BlockValidatedEvent.OutputTuple,
    BlockValidatedEvent.OutputObject
  >;
  getEvent(
    key: "StakeDeposited"
  ): TypedContractEvent<
    StakeDepositedEvent.InputTuple,
    StakeDepositedEvent.OutputTuple,
    StakeDepositedEvent.OutputObject
  >;
  getEvent(
    key: "StakeWithdrawn"
  ): TypedContractEvent<
    StakeWithdrawnEvent.InputTuple,
    StakeWithdrawnEvent.OutputTuple,
    StakeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorSlashed"
  ): TypedContractEvent<
    ValidatorSlashedEvent.InputTuple,
    ValidatorSlashedEvent.OutputTuple,
    ValidatorSlashedEvent.OutputObject
  >;

  filters: {
    "BlockValidated(uint256,uint256,bool)": TypedContractEvent<
      BlockValidatedEvent.InputTuple,
      BlockValidatedEvent.OutputTuple,
      BlockValidatedEvent.OutputObject
    >;
    BlockValidated: TypedContractEvent<
      BlockValidatedEvent.InputTuple,
      BlockValidatedEvent.OutputTuple,
      BlockValidatedEvent.OutputObject
    >;

    "StakeDeposited(address,uint256)": TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;
    StakeDeposited: TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;

    "StakeWithdrawn(address,uint256)": TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
    StakeWithdrawn: TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;

    "ValidatorSlashed(address,uint256,string)": TypedContractEvent<
      ValidatorSlashedEvent.InputTuple,
      ValidatorSlashedEvent.OutputTuple,
      ValidatorSlashedEvent.OutputObject
    >;
    ValidatorSlashed: TypedContractEvent<
      ValidatorSlashedEvent.InputTuple,
      ValidatorSlashedEvent.OutputTuple,
      ValidatorSlashedEvent.OutputObject
    >;
  };
}
