/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bridgeRouterSol from "./BridgeRouter.sol";
export type { bridgeRouterSol };
export type { IRelayer } from "./IRelayer";
