/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace FungibleFactory {
  export type PaymentTokenStruct = {
    ptTokenAddress: AddressLike;
    ptPriceFeed: AddressLike;
    ptUUSD_PER_TOKEN: BigNumberish;
    ptDecimals: BigNumberish;
    ptuUSDInvested: BigNumberish;
    ptAmountInvested: BigNumberish;
  };

  export type PaymentTokenStructOutput = [
    ptTokenAddress: string,
    ptPriceFeed: string,
    ptUUSD_PER_TOKEN: bigint,
    ptDecimals: bigint,
    ptuUSDInvested: bigint,
    ptAmountInvested: bigint
  ] & {
    ptTokenAddress: string;
    ptPriceFeed: string;
    ptUUSD_PER_TOKEN: bigint;
    ptDecimals: bigint;
    ptuUSDInvested: bigint;
    ptAmountInvested: bigint;
  };
}

export interface FungibleFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deletePaymentToken"
      | "getPaymentSymbols"
      | "getPaymentToken"
      | "setPaymentToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AddedPaymentToken" | "DeletedPaymentToken"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deletePaymentToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentSymbols",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentToken",
    values: [string, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deletePaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentSymbols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentToken",
    data: BytesLike
  ): Result;
}

export namespace AddedPaymentTokenEvent {
  export type InputTuple = [symbol: string];
  export type OutputTuple = [symbol: string];
  export interface OutputObject {
    symbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeletedPaymentTokenEvent {
  export type InputTuple = [symbol: string];
  export type OutputTuple = [symbol: string];
  export interface OutputObject {
    symbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FungibleFactory extends BaseContract {
  connect(runner?: ContractRunner | null): FungibleFactory;
  waitForDeployment(): Promise<this>;

  interface: FungibleFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deletePaymentToken: TypedContractMethod<
    [symbol: string, index: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPaymentSymbols: TypedContractMethod<[], [string[]], "view">;

  getPaymentToken: TypedContractMethod<
    [symbol: string],
    [FungibleFactory.PaymentTokenStructOutput],
    "view"
  >;

  setPaymentToken: TypedContractMethod<
    [
      symbol: string,
      tokenAdd: AddressLike,
      priceFeed: AddressLike,
      uUSDPerTokens: BigNumberish,
      decimals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deletePaymentToken"
  ): TypedContractMethod<
    [symbol: string, index: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPaymentSymbols"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPaymentToken"
  ): TypedContractMethod<
    [symbol: string],
    [FungibleFactory.PaymentTokenStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "setPaymentToken"
  ): TypedContractMethod<
    [
      symbol: string,
      tokenAdd: AddressLike,
      priceFeed: AddressLike,
      uUSDPerTokens: BigNumberish,
      decimals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddedPaymentToken"
  ): TypedContractEvent<
    AddedPaymentTokenEvent.InputTuple,
    AddedPaymentTokenEvent.OutputTuple,
    AddedPaymentTokenEvent.OutputObject
  >;
  getEvent(
    key: "DeletedPaymentToken"
  ): TypedContractEvent<
    DeletedPaymentTokenEvent.InputTuple,
    DeletedPaymentTokenEvent.OutputTuple,
    DeletedPaymentTokenEvent.OutputObject
  >;

  filters: {
    "AddedPaymentToken(string)": TypedContractEvent<
      AddedPaymentTokenEvent.InputTuple,
      AddedPaymentTokenEvent.OutputTuple,
      AddedPaymentTokenEvent.OutputObject
    >;
    AddedPaymentToken: TypedContractEvent<
      AddedPaymentTokenEvent.InputTuple,
      AddedPaymentTokenEvent.OutputTuple,
      AddedPaymentTokenEvent.OutputObject
    >;

    "DeletedPaymentToken(string)": TypedContractEvent<
      DeletedPaymentTokenEvent.InputTuple,
      DeletedPaymentTokenEvent.OutputTuple,
      DeletedPaymentTokenEvent.OutputObject
    >;
    DeletedPaymentToken: TypedContractEvent<
      DeletedPaymentTokenEvent.InputTuple,
      DeletedPaymentTokenEvent.OutputTuple,
      DeletedPaymentTokenEvent.OutputObject
    >;
  };
}
