/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace FungibleFactory {
  export type FacetVersionStruct = {
    facetVersion: string;
    facetAddress: AddressLike;
  };

  export type FacetVersionStructOutput = [
    facetVersion: string,
    facetAddress: string
  ] & { facetVersion: string; facetAddress: string };
}

export interface FungibleFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getFacetAddress"
      | "getFacetTypes"
      | "getFacetVersions"
      | "getFungible"
      | "getFungibles"
      | "getFungiblesByAddress"
      | "setFacetVersion"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getFacetAddress",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetTypes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetVersions",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getFungible", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getFungibles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFungiblesByAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFacetVersion",
    values: [string, string, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getFacetAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetVersions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFungible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFungibles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFungiblesByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFacetVersion",
    data: BytesLike
  ): Result;
}

export interface FungibleFactory extends BaseContract {
  connect(runner?: ContractRunner | null): FungibleFactory;
  waitForDeployment(): Promise<this>;

  interface: FungibleFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFacetAddress: TypedContractMethod<
    [facetType: string, facetVersion: string],
    [string],
    "view"
  >;

  getFacetTypes: TypedContractMethod<[], [string[]], "view">;

  getFacetVersions: TypedContractMethod<
    [facetType: string],
    [FungibleFactory.FacetVersionStructOutput[]],
    "view"
  >;

  getFungible: TypedContractMethod<[fungibleName: string], [string], "view">;

  getFungibles: TypedContractMethod<[], [string[]], "view">;

  getFungiblesByAddress: TypedContractMethod<
    [crytocommodityOwner: AddressLike],
    [string[]],
    "view"
  >;

  setFacetVersion: TypedContractMethod<
    [facetType: string, facetVersion: string, facetAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFacetAddress"
  ): TypedContractMethod<
    [facetType: string, facetVersion: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFacetTypes"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getFacetVersions"
  ): TypedContractMethod<
    [facetType: string],
    [FungibleFactory.FacetVersionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFungible"
  ): TypedContractMethod<[fungibleName: string], [string], "view">;
  getFunction(
    nameOrSignature: "getFungibles"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getFungiblesByAddress"
  ): TypedContractMethod<
    [crytocommodityOwner: AddressLike],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "setFacetVersion"
  ): TypedContractMethod<
    [facetType: string, facetVersion: string, facetAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
