/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface NodeTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCrossChainValidator"
      | "addValidator"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "blocks"
      | "chainId"
      | "createTransaction"
      | "crossChainValidators"
      | "currentBlockNumber"
      | "decimals"
      | "executeCrossChainTransaction"
      | "getBlock"
      | "getChainState"
      | "getPendingTransactions"
      | "getTransaction"
      | "name"
      | "nonces"
      | "owner"
      | "pendingTransactions"
      | "removeValidator"
      | "requiredConfirmations"
      | "submitBlock"
      | "symbol"
      | "totalSupply"
      | "transactions"
      | "transfer"
      | "transferFrom"
      | "validators"
      | "verifyBlock"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "BlockAdded"
      | "CrossChainTransactionExecuted"
      | "TransactionCreated"
      | "Transfer"
      | "ValidatorAdded"
      | "ValidatorRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCrossChainValidator",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addValidator",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blocks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "chainId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createTransaction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "crossChainValidators",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentBlockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeCrossChainTransaction",
    values: [BytesLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingTransactions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredConfirmations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitBlock",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBlock",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCrossChainValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "blocks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "crossChainValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeCrossChainTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChainState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validators", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyBlock",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlockAddedEvent {
  export type InputTuple = [
    blockNumber: BigNumberish,
    blockHash: BytesLike,
    validator: AddressLike
  ];
  export type OutputTuple = [
    blockNumber: bigint,
    blockHash: string,
    validator: string
  ];
  export interface OutputObject {
    blockNumber: bigint;
    blockHash: string;
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainTransactionExecutedEvent {
  export type InputTuple = [txHash: BytesLike, sourceChainId: BigNumberish];
  export type OutputTuple = [txHash: string, sourceChainId: bigint];
  export interface OutputObject {
    txHash: string;
    sourceChainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionCreatedEvent {
  export type InputTuple = [
    txHash: BytesLike,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    txHash: string,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    txHash: string;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorAddedEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRemovedEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NodeToken extends BaseContract {
  connect(runner?: ContractRunner | null): NodeToken;
  waitForDeployment(): Promise<this>;

  interface: NodeTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCrossChainValidator: TypedContractMethod<
    [targetChainId: BigNumberish, validator: AddressLike],
    [void],
    "nonpayable"
  >;

  addValidator: TypedContractMethod<
    [validator: AddressLike, stake: BigNumberish],
    [void],
    "nonpayable"
  >;

  allowance: TypedContractMethod<
    [owner_: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  blocks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, bigint, string, string, bigint] & {
        blockHash: string;
        blockNumber: bigint;
        previousHash: string;
        timestamp: bigint;
        data: string;
        validator: string;
        chainId: bigint;
      }
    ],
    "view"
  >;

  chainId: TypedContractMethod<[], [bigint], "view">;

  createTransaction: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;

  crossChainValidators: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  currentBlockNumber: TypedContractMethod<[], [bigint], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  executeCrossChainTransaction: TypedContractMethod<
    [txHash: BytesLike, sourceChainId: BigNumberish, signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  getBlock: TypedContractMethod<
    [blockNumber: BigNumberish],
    [
      [string, bigint, string, bigint, string, string, bigint, string[]] & {
        blockHash: string;
        _blockNumber: bigint;
        previousHash: string;
        timestamp: bigint;
        data: string;
        validator: string;
        _chainId: bigint;
        transactionHashes: string[];
      }
    ],
    "view"
  >;

  getChainState: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        _chainId: bigint;
        _currentBlockNumber: bigint;
        totalBlocks: bigint;
        totalTransactions: bigint;
        pendingCount: bigint;
        activeValidators: bigint;
        _totalSupply: bigint;
      }
    ],
    "view"
  >;

  getPendingTransactions: TypedContractMethod<[], [string[]], "view">;

  getTransaction: TypedContractMethod<
    [txHash: BytesLike],
    [
      [string, string, bigint, bigint, string, boolean, bigint, bigint] & {
        from: string;
        to: string;
        amount: bigint;
        timestamp: bigint;
        _txHash: string;
        executed: boolean;
        _chainId: bigint;
        nonce: bigint;
      }
    ],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingTransactions: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  removeValidator: TypedContractMethod<
    [validator: AddressLike],
    [void],
    "nonpayable"
  >;

  requiredConfirmations: TypedContractMethod<[], [bigint], "view">;

  submitBlock: TypedContractMethod<
    [data: BytesLike, transactionHashes: BytesLike[]],
    [bigint],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transactions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, boolean, bigint, bigint] & {
        from: string;
        to: string;
        amount: bigint;
        timestamp: bigint;
        txHash: string;
        executed: boolean;
        chainId: bigint;
        nonce: bigint;
      }
    ],
    "view"
  >;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  validators: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, boolean, bigint] & {
        validatorAddress: string;
        stake: bigint;
        isActive: boolean;
        lastValidated: bigint;
      }
    ],
    "view"
  >;

  verifyBlock: TypedContractMethod<
    [blockNumber: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCrossChainValidator"
  ): TypedContractMethod<
    [targetChainId: BigNumberish, validator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addValidator"
  ): TypedContractMethod<
    [validator: AddressLike, stake: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner_: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "blocks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, bigint, string, string, bigint] & {
        blockHash: string;
        blockNumber: bigint;
        previousHash: string;
        timestamp: bigint;
        data: string;
        validator: string;
        chainId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "chainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createTransaction"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "crossChainValidators"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentBlockNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeCrossChainTransaction"
  ): TypedContractMethod<
    [txHash: BytesLike, sourceChainId: BigNumberish, signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBlock"
  ): TypedContractMethod<
    [blockNumber: BigNumberish],
    [
      [string, bigint, string, bigint, string, string, bigint, string[]] & {
        blockHash: string;
        _blockNumber: bigint;
        previousHash: string;
        timestamp: bigint;
        data: string;
        validator: string;
        _chainId: bigint;
        transactionHashes: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChainState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        _chainId: bigint;
        _currentBlockNumber: bigint;
        totalBlocks: bigint;
        totalTransactions: bigint;
        pendingCount: bigint;
        activeValidators: bigint;
        _totalSupply: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingTransactions"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTransaction"
  ): TypedContractMethod<
    [txHash: BytesLike],
    [
      [string, string, bigint, bigint, string, boolean, bigint, bigint] & {
        from: string;
        to: string;
        amount: bigint;
        timestamp: bigint;
        _txHash: string;
        executed: boolean;
        _chainId: bigint;
        nonce: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingTransactions"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "removeValidator"
  ): TypedContractMethod<[validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requiredConfirmations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitBlock"
  ): TypedContractMethod<
    [data: BytesLike, transactionHashes: BytesLike[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, boolean, bigint, bigint] & {
        from: string;
        to: string;
        amount: bigint;
        timestamp: bigint;
        txHash: string;
        executed: boolean;
        chainId: bigint;
        nonce: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validators"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, boolean, bigint] & {
        validatorAddress: string;
        stake: bigint;
        isActive: boolean;
        lastValidated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyBlock"
  ): TypedContractMethod<[blockNumber: BigNumberish], [boolean], "view">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "BlockAdded"
  ): TypedContractEvent<
    BlockAddedEvent.InputTuple,
    BlockAddedEvent.OutputTuple,
    BlockAddedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainTransactionExecuted"
  ): TypedContractEvent<
    CrossChainTransactionExecutedEvent.InputTuple,
    CrossChainTransactionExecutedEvent.OutputTuple,
    CrossChainTransactionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionCreated"
  ): TypedContractEvent<
    TransactionCreatedEvent.InputTuple,
    TransactionCreatedEvent.OutputTuple,
    TransactionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorAdded"
  ): TypedContractEvent<
    ValidatorAddedEvent.InputTuple,
    ValidatorAddedEvent.OutputTuple,
    ValidatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRemoved"
  ): TypedContractEvent<
    ValidatorRemovedEvent.InputTuple,
    ValidatorRemovedEvent.OutputTuple,
    ValidatorRemovedEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "BlockAdded(uint256,bytes32,address)": TypedContractEvent<
      BlockAddedEvent.InputTuple,
      BlockAddedEvent.OutputTuple,
      BlockAddedEvent.OutputObject
    >;
    BlockAdded: TypedContractEvent<
      BlockAddedEvent.InputTuple,
      BlockAddedEvent.OutputTuple,
      BlockAddedEvent.OutputObject
    >;

    "CrossChainTransactionExecuted(bytes32,uint256)": TypedContractEvent<
      CrossChainTransactionExecutedEvent.InputTuple,
      CrossChainTransactionExecutedEvent.OutputTuple,
      CrossChainTransactionExecutedEvent.OutputObject
    >;
    CrossChainTransactionExecuted: TypedContractEvent<
      CrossChainTransactionExecutedEvent.InputTuple,
      CrossChainTransactionExecutedEvent.OutputTuple,
      CrossChainTransactionExecutedEvent.OutputObject
    >;

    "TransactionCreated(bytes32,address,address,uint256)": TypedContractEvent<
      TransactionCreatedEvent.InputTuple,
      TransactionCreatedEvent.OutputTuple,
      TransactionCreatedEvent.OutputObject
    >;
    TransactionCreated: TypedContractEvent<
      TransactionCreatedEvent.InputTuple,
      TransactionCreatedEvent.OutputTuple,
      TransactionCreatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "ValidatorAdded(address)": TypedContractEvent<
      ValidatorAddedEvent.InputTuple,
      ValidatorAddedEvent.OutputTuple,
      ValidatorAddedEvent.OutputObject
    >;
    ValidatorAdded: TypedContractEvent<
      ValidatorAddedEvent.InputTuple,
      ValidatorAddedEvent.OutputTuple,
      ValidatorAddedEvent.OutputObject
    >;

    "ValidatorRemoved(address)": TypedContractEvent<
      ValidatorRemovedEvent.InputTuple,
      ValidatorRemovedEvent.OutputTuple,
      ValidatorRemovedEvent.OutputObject
    >;
    ValidatorRemoved: TypedContractEvent<
      ValidatorRemovedEvent.InputTuple,
      ValidatorRemovedEvent.OutputTuple,
      ValidatorRemovedEvent.OutputObject
    >;
  };
}
