/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bridgeRouterSol from "./BridgeRouter.sol";
export { IRelayer__factory } from "./IRelayer__factory";
